apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: insecure-pizza-coffee
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "pizzacoffee"
  DD_SITE: "datadoghq.com"
  DD_SERVICE: "insecure-pizza-coffee"
  DD_ENV: "production"
  DD_VERSION: "1.0.0"
  DD_TRACE_ENABLED: "true"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  DD_PROFILING_ENABLED: "true"
  DD_APPSEC_ENABLED: "true"
  DD_APPSEC_SCA_ENABLED: "true"
  DD_IAST_ENABLED: "true"
  DD_REMOTE_CONFIGURATION_ENABLED: "true"
  DD_AGENT_HOST: "datadog-agent.datadog.svc.cluster.local"
  DD_TRACE_AGENT_PORT: "8126"
